### ISSUE TITLE
Issues with the /app/init-container.py

### ISSUE THREAD

**Issue by fgka** [Senzing/docker-wrap-image-with-senzing-apt#18]
**Describe the bug**
Container initialization ([Dockerfile line 43](https://github.com/Senzing/docker-wrap-image-with-senzing-apt/blob/b0b96654ac8d68fc87581be27b45748a8b57bcbe/Dockerfile#L43)) does not work: 

```
Traceback (most recent call last):
  File "/app/init-container.py", line 1680, in <module>
    globals()[subcommand_function_name](args)
  File "/app/init-container.py", line 1559, in do_initialize_files
    change_project_ini(config)
  File "/app/init-container.py", line 989, in change_project_ini
    old_database_url = config_parser.get('g2', 'G2Connection')
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'g2'
```

**To Reproduce**

```
docker build --build-arg BASE_IMAGE="senzing/senzing-api-server:2.0.0" --build-arg SENZING_ACCEPT_EULA=I_ACCEPT_THE_SENZING_EULA https://github.com/Senzing/docker-wrap-image-with-senzing-apt.git
```

It expected the file (that does not exist): `/etc/opt/senzing/G2Project.ini`

The files available are:
```
ls /etc/opt/senzing/
G2Module.ini  cfgVariant.json  customGn.txt  customOn.txt  customSn.txt  defaultGNRCP.config  g2config.json  stb.config
```

**Expected behavior**
Should just work

**Desktop (please complete the following information):**

- Device: MacBookAir9,1 (Intel)
- OS: macOS 11.3 (20E232)
- Docker: Docker version 20.10.5, build 55c4c88

**Comment by jeffadair** [comment]
@fgka I was able to reproduce this and was able to get it building by changing [line 42](https://github.com/Senzing/docker-wrap-image-with-senzing-apt/blob/b0b96654ac8d68fc87581be27b45748a8b57bcbe/Dockerfile#L42) to:

`COPY --from=senzing/init-container:1.6.9  "/app/init-container.py" "/app/init-container.py"`

This is updating to the latest init-container version. I'll create a PR to get this change properly reviewed, but until then give this a try and see if it works for you.

**Comment by fgka** [comment]
Hi Jeff,

I've just tested and it works perfectly, thank you very much for the prompt response.

Cheers,

Gustavi

**Comment by jeffadair** [comment]
Gustavo (@fgka )

Glad to hear it!

FYI, I've created a new release ([1.0.4](https://github.com/Senzing/docker-wrap-image-with-senzing-apt/releases/tag/1.0.4)) with the changes. I'd suggest using it instead of local edits.

If you are satisfied with this fix, please close this issue. If we don't hear back in a week we'll close it assuming it is fixed. Feel free to reopen at that point it if it is not.

**Comment by fgka** [comment]
Thanks, this issue can be closed :-)
